# comment
FROM ubuntu:14.04
MAINTAINER image-test <mesh1neko@gmail.com>
#RUN apt-get update && apt-get install -y vim
#CMD ["ping", "-c", "30", "127.0.0.1"]
#ENTRYPOINT ["ping", "-c", "3"]
#CMD ["127.0.0.1"]
#ENV FOO bar
#WORKDIR /home/root/
#ADD file.tar.gz .
#RUN mkdir -p /data/myvol && \
#echo "hello from dockerfile volume." > /data/myvol/init.txt
#VOLUME /data/myvol
EXPOSE 80 443
